### ISSUE TITLE
On Start button click Error

### ISSUE THREAD

**Issue by mansoorulhaq324** [OwnDing/Async_Await_TCP_Server#1]
WHen I am running it is showing SQLLite relate error:
![image](https://user-images.githubusercontent.com/42800922/54829043-5e94cb00-4cd7-11e9-806a-d34f98bcbfe2.png)

**Comment by OwnDing** [comment]
Hi
The System.Data.SQLite.dll file is corrupted.
You can go to 
[http://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki](url)
to download the correct dll file.
<img width="1087" alt="1" src="https://user-images.githubusercontent.com/13973203/54861752-9fd5bb00-4d69-11e9-904f-e987d8566abd.PNG">

Hope this helps.
